widget/discrepancy-note/Dn.js

Fix for the error that was resulting in "alert.gotohidden.msg"

OC-9285, fix for alert.goto.hidden message

---

app/views/styles/component/_print-oc.scss

#275 
https://jira.openclinica.com/browse/OC-11951

update: OC: DN history, remove borders + padding

---

widget/discrepancy-note/dn-widget.js

#271 
https://jira.openclinica.com/browse/OC-11781

fixed: OC: Printed form not displaying '/' character in history label

---

widget/discrepancy-note/dn-widget.scss

#307 [OC-12232](https://jira.openclinica.com/browse/OC-12232)

fixed: OC: Query Widget text issue if parent item has columns-n appearance

---

widget/discrepancy-note/dn-widget.js

#299 [OC-12195](https://jira.openclinica.com/browse/OC-12195)

fixed: OC: Update Query Widget modal focus

---

widget/discrepancy-note/dn-widget.js

fixed: OC: Sometimes defaultAssignee is not determined correctly in DN widget

---

app/views/layout.pug
app/views/surveys/webform.pug

#388 
'nomodule' type script is not working on Edge that why the polyfill script is not loaded and the form not opened.

fixed: OC: Edge Legacy regression - no forms open

---

Gruntfile.js
app/views/surveys/webform.pug
package-lock.json
package.json

fixed: OC: IE 11 and Edge Legacy - can't load external data(add polyfill for CSS.escape)

---

Gruntfile.js

fixed: IE11/Edge Legacy - Choice Filter items not working correctly

---

Gruntfile.js
package-lock.json
package.json

fixed: OC: IE11/Edge Legacy - Choice Filter items not working correctly

---

public/js/src/module/reasons.js

fixed: OC: Close button on completed form not working

---

Gruntfile.js

fixed: OC: IE11/Edge Legacy - Choice Filter items not working correctly(update Gruntfile)

---

widget/discrepancy-note/dn-widget.js

fixed: OC: when opening form and automatically going to dn widget on an image-map question, the image map ends up in the dn modal(add delay)

---

public/js/src/module/gui.js

fixed: OC: Issue With Printing Single Select Items with Minimal Display on Chrome and Edge

---

app/lib/communicator.js
locales/src/en/translation-additions.json

[OC-17706](https://jira.openclinica.com/browse/OC-17706) Update Clear Storage Button Text
[OC-17826](https://jira.openclinica.com/browse/OC-17826) Update translation-additions.json file with support email token
Hi, @MartijnR ~ I found the error then running grunt develop on the communicator.js
```
SyntaxError: Unexpected token '.'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> …
```

OC-17706 Update Clear Storage Button Text & OC-17826 Update translation-additions.json file with support email token

---

locales/src/en/translation-additions.json

update: oc: Change App Name "Enketo" and "KoBoCAT"

---

locales/src/en/translation-additions.json

update: oc: update enketo refresh message(offline form[feedback])

---

package-lock.json
package.json
public/js/src/enketo-webform-oc.js
public/js/src/module/field-submission-queue.js

Fixes translation issues with all fieldsubmission feedback messages.
Also did some maintenance by removing jQuery from the code that deals with this.
Also fixed a bug where a 'disabled' feedback message was not displayed (invalid function call).

fixed: fieldsubmission feedback not translated properly, #613

---

README.md

Closes #645
I had to add some (readme.md) changes to get this PR to be accepted, because it's just the git tag that is different which is not considered a change, I believe.

Merge/release 6.0.0 second try

---

public/js/src/module/controller-webform-oc.js

fixed: closing completed form provides no autoquery option, #649

---

public/js/src/module/controller-webform-oc.js

fixed: previews are submitting data, #647

---

public/js/src/module/controller-webform-oc.js

Closes #667
This simply adds an if-clause for previews to not enable the external signature feature (though the diff may appear more than that).

fixed: disable external-signature feature in previews, #667

---

locales/src/de/translation-additions.json
locales/src/de/translation.json

OC-20640: Translate Stack 18 i18n properties files

OC-20640: Translate Stack 18 i18n properties files

---

locales/src/de/translation-additions.json
locales/src/de/translation.json

Reverts OpenClinica/enketo-express-oc#673

Revert "OC-20640: Translate Stack 18 i18n properties files"

---

locales/src/de/translation-additions.json

Closes #
-   [ ] Online form submission
-   [ ] Offline form submission
-   [ ] Saving offline drafts
-   [ ] Loading offline drafts
-   [ ] Editing submissions
-   [ ] Form preview
-   [ ] None of the above

Fixing de translations file

---

app/views/styles/component/_common-oc.scss
app/views/surveys/component/_form-footer.pug
app/views/surveys/dev.pug
locales/src/en/translation.json
public/js/src/module/controller-webform-oc.js
public/js/src/module/event.js

added ‘Finish Later' button in fieldsubmission Participate views, #674

---

app/lib/headless-browser.js

Reverts OpenClinica/enketo-express-oc#700

Revert "Fix/pdf analog scale 671"

---

config/build.js

Reverts OpenClinica/enketo-express-oc#696

Revert "fixed: regression due to code splitting in esbuild"

---

config/build.js

Reverts OpenClinica/enketo-express-oc#703

Revert "Revert "fixed: regression due to code splitting in esbuild""

---

app/lib/headless-browser.js

Reverts OpenClinica/enketo-express-oc#701

Revert "Revert "Fix/pdf analog scale 671""

---

app/views/surveys/component/_form-footer.pug

#708
No risks. Can be merged after all the reversals.

fixed: back button translation not switching, #708

---

widget/discrepancy-note/dn-widget.js

fixed: dn comments are not HTML encoded, #718

---

public/js/src/module/controller-webform-oc.js
public/js/src/module/page.js
widget/discrepancy-note/dn-widget.js

Closes #
-   [ ] Online form submission
-   [ ] Offline form submission
-   [ ] Saving offline drafts
-   [ ] Loading offline drafts
-   [ ] Editing submissions
-   [ ] Form preview
-   [ ] None of the above

Merging latest master into 6.2.2.oc

---

test/client/dn-widget.spec.js
widget/discrepancy-note/dn-widget.js

OC-16858 Attribute autoqueries to system user

---

locales/src/en/translation.json

OC-20751 Add "Finish Later" button to Participate forms(Update translation)
